INSERT INTO stat_information 
VALUES 
(1, 1, 'Passing Attempts', 'Pass Att', 'passing', 'Att', 1, 'O'),
(2, 1, 'Passing Completions', 'Pass Comp', 'passing', 'Comp', 1, 'O'), 
(4, 1, 'Passing Yards', 'Pass Yds', 'passing', 'Yds', 1, 'O'),
(5, 1, 'Passing Touchdowns', 'Pass TD', 'passing', 'TD', 1, 'O'),
(6, 1, 'Interceptions', 'Int', 'passing', 'Int', 0, 'O'),
(8, 1, 'Rushing Attempts', 'Rush Att', 'rushing', 'Att', 1, 'O'),
(9, 1, 'Rushing Yards', 'Rush Yds', 'rushing', 'Yds', 1, 'O'),
(10, 1, 'Rushing Touchdowns', 'Rush TD', 'rushing', 'TD', 1, 'O'),
(11, 1, 'Receptions', 'Rec', 'receiving', 'Rec', 1, 'O'),
(12, 1, 'Receiving Yards', 'Rec Yds', 'receiving', 'Yds', 1, 'O'),
(13, 1, 'Receiving Touchdowns', 'Rec TD', 'receiving', 'TD', 1, 'O'),
(15, 1, 'Return Touchdowns', 'Ret Td', 'return', 'TD', 1, 'O'),
(16, 1, '2-Point Conversion', '2-PT', 'misc', '2-PT', 1, 'O'),
(18, 1, 'Fumbles Lost', 'Fum Lost', 'fumbles', 'Lost', 0, 'O'),
(78, 1, 'Targets', 'Targets', 'receiving', 'Targets', 1, 'O'),
(57, 1, 'Offensive Fumble Return TD', 'Fum Ret TD', 'misc', 'Off Fumb TD', 1, 'O'),
(19, 1, 'Field Goals 0-19 Yards', 'FG 0-19', 'fgs', '0-19 Yds', 1, 'K'),
(20, 1, 'Field Goals 20-29 Yards', 'FG 20-29', 'fgs', '20-29 Yds', 1, 'K'),
(21, 1, 'Field Goals 30-39 Yards', 'FG 30-39', 'fgs', '30-39 Yds', 1, 'K'),
(22, 1, 'Field Goals 40-49 Yards', 'FG 40-49', 'fgs', '40-49 Yds', 1, 'K'),
(23, 1, 'Field Goals 50+ Yds', 'FG 50+', 'fgs', '50+', 1, 'K'),
(29, 1, 'Point After Attempt Made', 'PAT Made', 'pat', 'Made', 1, 'K'),
(31, 1, 'Points Allowed', 'Pts Allowed', 'none', 'Pts vs.', 0, 'DT'),
(32, 1, 'Sack', 'Sack', 'team_tackles', 'Sack', 1, 'DT'),
(33, 1, 'Interception', 'Int', 'def_turnovers', 'Int', 1, 'DT'),
(34, 1, 'Fumble Recovery', 'Fum Rec', 'def_turnovers', 'Fum Rec', 1, 'DT'),
(35, 1, 'Touchdown', 'TD', 'tds', 'TD', 1, 'DT'),
(36, 1, 'Safety', 'Safe', 'team_tackles', 'Safe', 1, 'DT'),
(37, 1, 'Block Kick', 'Blk Kick', 'misc', 'Blk Kick', 1, 'DT'),
(49, 1, 'Kickoff and Punt Return Touchdowns', 'Ret Td', 'return', 'TD', 1, 'DT'),
(50, 1, 'Points Allowed 0 points', 'Pts Allowed 0', 'pts_allowed', '0 Pts', 1, 'DT'),
(51, 1, 'Points Allowed 1-6 points', 'Pts Allowed 1-6 Pts', 'pts_allowed', '1-6 Pts', 1, 'DT'),
(52, 1, 'Points Allowed 7-13 points', 'Pts Allowed 7-13', 'pts_allowed', '7-13 Pts', 1, 'DT'),
(53, 1, 'Points Allowed 14-20 points', 'Pts Allowed 14-20', 'pts_allowed', '14-20 Pts', 1, 'DT'),
(54, 1, 'Points Allowed 21-27 points', 'Pts Allowed 21-27', 'pts_allowed', '21-27 Pts', 1, 'DT'),
(55, 1, 'Points Allowed 28-34 points', 'Pts Allowed 28-34', 'pts_allowed', '28-34 Pts', 1, 'DT'),
(56, 1, 'Points Allowed 35+ points', 'Pts Allowed 35+', 'pts_allowed', '35+ Pts', 1, 'DT'),
(82, 1, 'Extra Point Returned', 'XPR', 'misc', 'XPR', 1, 'DT')